# Limit lines to 79 characters.
LineLength:
  Max: 79

# Avoid methods longer than 15 lines of code
MethodLength:
  CountComments: false  # count full line comments?
  Max: 15

# We like Ruby 1.8 hash syntax for dynamic key support
HashSyntax:
  Enabled: false

# Classes don't need top-level comments
Documentation:
  Enabled: false
